# >>> PRIMER MANAGED START (modules/kde-desktop-settings/files/ghostty/keybinds.conf) >>>
keybind = cmd+backspace=text:\x15
keybind = shift+insert=paste_from_clipboard
keybind = alt+backspace=text:\x17
keybind = alt+delete=esc:d
keybind = ctrl+backspace=text:\x17
keybind = ctrl+delete=esc:d
keybind = shift+home=text:\x15
keybind = shift+end=text:\x0b
keybind = ctrl+alt+shift+d=new_split:right
keybind = ctrl+alt+shift+f=new_split:down
keybind = ctrl+alt+shift+t=new_tab
keybind = ctrl+alt+shift+w=close_surface
keybind = cmd+ctrl+left=goto_split:left
keybind = cmd+ctrl+right=goto_split:right
keybind = cmd+ctrl+up=goto_split:top
keybind = cmd+ctrl+down=goto_split:bottom
# <<< PRIMER MANAGED END (modules/kde-desktop-settings/files/ghostty/keybinds.conf) <<<
